### Получение сотрудника с максимальной зарплатой
GET http://localhost:8080/employee/salary/max
Content-Type: application/json

### Получение сотрудника с минимальной зарплатой
GET http://localhost:8080/employee/salary/min
Content-Type: application/json

### Получение сумм зарплат сотрудников
GET http://localhost:8080/employee/salary/sum
Content-Type: application/json

### Получение сотрудников с зарплатой выше среднего
GET http://localhost:8080/employee/salary/aboveAverage
Content-Type: application/json

### Получение всех сотрудников
GET http://localhost:8080/employee/all
Content-Type: application/json

### Получение сотрудника по id
GET http://localhost:8080/employee/66
Content-Type: application/json

### Создание сотрудников
POST http://localhost:8080/employee/employeeList
Content-Type: application/json

[
  {
    "name": "Артем",
    "salary": 110000,
    "position": {
      "id": 2,
      "position": "QA"
    }
  },
  {
    "name": "Вова",
    "salary": 90000,
    "position": {
      "id": 1,
      "position": "Программист"
    }
  }
]

### Обновление сотрудника по id
PUT http://localhost:8080/employee/66
Content-Type: application/json

{
  "name": "Игорь",
  "salary": 95000,
  "position": {
    "id": 1,
    "position": "Программист"
  }
}

### Удаление сотрудника
DELETE http://localhost:8080/employee/65

### Получение сотрудников с зарплатой больше чем
GET http://localhost:8080/employee/salary/higherThan?salary=30000
Content-Type: application/json

### Получение сотрудников по позиции
GET http://localhost:8080/employee?position=П
Content-Type: application/json

### Получение сотрудников по странице
GET http://localhost:8080/employee/page?page=0
Content-Type: application/json

### Получение сотрудника(ов) с наибольшей зарплатой
GET http://localhost:8080/employee/withHighSalary
Content-Type: application/json

### Создание рапорта
POST http://localhost:8080/report

### Получение рапорта по ID
GET http://localhost:8080/report/5

### Загрузка файла с сотрудниками в БД
POST http://localhost:8080/employee/upload
#Authorization: Basic dXNLcjoxMjMONTY=
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="employees"; filename="employees.json"
Content-Type: application/json

< ./employees.json
--WebAppBoundary--

### Получение рапорт файла по ID
GET http://localhost:8080/report/file/4